spring:
  profiles:
    active: local
    group:
        "local": "local, jwt, oauth"
        enable: true
  datasource:
    url: jdbc:h2:./test
    driver-class-name: org.h2.Driver
    username: sa
    password: 3232
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    cache: false
    check-template-location: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 956464906378-ksrqt4kb7s7kv4a7q1qfa3qnpj65nclt.apps.googleusercontent.com
            client-secret: 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
