spring:
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: local
    group:
        "local": "local, jwt, oauth"
        enable: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 3232
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    cache: false
    check-template-location: true